# Generated by Django 2.1.7 on 2019-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField()),
                ('level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('Phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=6)),
            ],
        ),
    ]
